In [ ]:
import numpy as np
import pandas as pd
import matplotlib. pyplot as plt

In [ ]:
dataset = pd.read_csv("insurance.csv")
dataset

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
dataset.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
dataset ['sex']= np.where(dataset['sex']=="female",1,0)
dataset

age  sex     bmi  children smoker     region      charges
0      19    1  27.900         0    yes  southwest  16884.92400
1      18    0  33.770         1     no  southeast   1725.55230
2      28    0  33.000         3     no  southeast   4449.46200
3      33    0  22.705         0     no  northwest  21984.47061
4      32    0  28.880         0     no  northwest   3866.85520
...   ...  ...     ...       ...    ...        ...          ...
1333   50    0  30.970         3     no  northwest  10600.54830
1334   18    1  31.920         0     no  northeast   2205.98080
1335   18    1  36.850         0     no  southeast   1629.83350
1336   21    1  25.800         0     no  southwest   2007.94500
1337   61    1  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
dataset['smoker']=np.where(dataset['smoker']=="yes",1,0)

In [ ]:
dataset

age  sex     bmi  children  smoker     region      charges
0      19    1  27.900         0       1  southwest  16884.92400
1      18    0  33.770         1       0  southeast   1725.55230
2      28    0  33.000         3       0  southeast   4449.46200
3      33    0  22.705         0       0  northwest  21984.47061
4      32    0  28.880         0       0  northwest   3866.85520
...   ...  ...     ...       ...     ...        ...          ...
1333   50    0  30.970         3       0  northwest  10600.54830
1334   18    1  31.920         0       0  northeast   2205.98080
1335   18    1  36.850         0       0  southeast   1629.83350
1336   21    1  25.800         0       0  southwest   2007.94500
1337   61    1  29.070         0       1  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
y_train= np.array(dataset.iloc[:,-1])
y_train =y_train.reshape(y_train.shape[0],1)
#[1338,]
y_train

array([[16884.924 ],
       [ 1725.5523],
       [ 4449.462 ],
       ...,
       [ 1629.8335],
       [ 2007.945 ],
       [29141.3603]])

In [ ]:
dataset = dataset.drop(columns=['charges'])

In [ ]:
dataset = pd.get_dummies(dataset, columns=['region'])

In [ ]:
dataset

age  sex     bmi  ...  region_northwest  region_southeast  region_southwest
0      19    1  27.900  ...                 0                 0                 1
1      18    0  33.770  ...                 0                 1                 0
2      28    0  33.000  ...                 0                 1                 0
3      33    0  22.705  ...                 1                 0                 0
4      32    0  28.880  ...                 1                 0                 0
...   ...  ...     ...  ...               ...               ...               ...
1333   50    0  30.970  ...                 1                 0                 0
1334   18    1  31.920  ...                 0                 0                 0
1335   18    1  36.850  ...                 0                 1                 0
1336   21    1  25.800  ...                 0                 0                 1
1337   61    1  29.070  ...                 1                 0                 0

[1338 rows x 9 columns]

In [ ]:
# converts dataset to an array and puts all rows and all column minus the last one
x_train = np.array(dataset.iloc[:, :])  #(1338,16)
# x_train = np.array(dataset.iloc[:,0:len(dataset.iloc[0,:])-1])


In [ ]:
x_train

array([[19.  ,  1.  , 27.9 , ...,  0.  ,  0.  ,  1.  ],
       [18.  ,  0.  , 33.77, ...,  0.  ,  1.  ,  0.  ],
       [28.  ,  0.  , 33.  , ...,  0.  ,  1.  ,  0.  ],
       ...,
       [18.  ,  1.  , 36.85, ...,  0.  ,  1.  ,  0.  ],
       [21.  ,  1.  , 25.8 , ...,  0.  ,  0.  ,  1.  ],
       [61.  ,  1.  , 29.07, ...,  1.  ,  0.  ,  0.  ]])

In [ ]:
print(x_train.shape)
print(y_train.shape)

(1338, 9)
(1338, 1)


In [ ]:
x_train = np.append(np.ones((x_train.shape[0],1)),x_train,axis=1)

In [ ]:
x_train.shape

(1338, 10)

In [ ]:
x_train

array([[ 1., 19.,  1., ...,  0.,  0.,  1.],
       [ 1., 18.,  0., ...,  0.,  1.,  0.],
       [ 1., 28.,  0., ...,  0.,  1.,  0.],
       ...,
       [ 1., 18.,  1., ...,  0.,  1.,  0.],
       [ 1., 21.,  1., ...,  0.,  0.,  1.],
       [ 1., 61.,  1., ...,  1.,  0.,  0.]])

In [ ]:
# x_train shape (1338,10)
#y_train shape (1338,1)
#thetas shape should be (1,10)


In [ ]:
def predictions (features, thetas):
  predictions = None # empty list
  if(thetas.shape!=(features.shape[1],1)):
    thetas=thetas.T
  predictions = np.dot(features,thetas)
  #print("predictions shape ",predictions.shape)
  return predictions

In [ ]:
def mean_square_error(features,thetas,goal):
  error = 0
  rows = features.shape[0]
  hypothesis = predictions(features,thetas.T)
 # print("hypothesis shape " , hypothesis.shape)
 # print("y_train shape ",goal.shape)
  #(1/(2*m))*np.sum(np.square((h-Y)),axis=0)
  #print ((goal.T-hypothesis.T).shape)
  error = (1/(2*rows)) * np.sum(np.square((goal-hypothesis).T),axis =1)
  #print("error is " ,error)
  #print("                                        ")
  return error 

In [ ]:
def gradient_descent (features,goal,lr,boundary,thetas):
  rows = features.shape[0]
  thetas = thetas.T
  for ctr in range(boundary):
    hypothesis = predictions(features,thetas.T)
    #print("hypothesis shape",hypothesis.shape)
    #error = hypothesis-goal
    #print("error shape",error.shape)
    #error = error.T
    #print("error transpose shape",error.shape)
    #print("np.dot(error,features) shape",np.dot(error,features).shape)
    #print("thetas shape ",thetas.shape)
    #rate = (lr/rows)*np.dot(error,features)
    #print("rate is ",rate)
    #print("equation shape ",((lr/columns)*((hypothesis-goal).T).dot(features)).shape)
    thetas = thetas - ((lr/rows)*(((hypothesis.T-goal.T)).dot(features)).T)
    #print("thetas shape after minusing",thetas.shape)
    #print("                  ")
    #print(thetas.shape)
  return thetas 

In [ ]:

thetas = np.ones((1,x_train.shape[1]),dtype=float)
print(thetas)
print(thetas.shape)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
(1, 10)


In [ ]:
print(x_train.shape)
print(y_train.shape)
print(thetas.shape)

(1338, 10)
(1338, 1)
(1, 10)


In [ ]:
learning_rate = 0.000000001
iterations =100

In [ ]:
thetas = gradient_descent(x_train,y_train,learning_rate,iterations,thetas)
thetas

array([[1.0013195 ],
       [1.05679611],
       [1.00061815],
       [1.04191929],
       [1.00154371],
       [1.00065479],
       [1.00032285],
       [1.00029983],
       [1.00039876],
       [1.00029807]])

In [ ]:
cost = mean_square_error(x_train,thetas,y_train)
cost

array([1.60228866e+08])

In [ ]:
first = np.dot(x_train.T,x_train)  
first.shape

(10, 10)

In [ ]:
first= (np.linalg.inv(first))

In [ ]:
first.shape

In [ ]:
second= np.dot(x_train.T,y_train)

In [ ]:
second.shape

(10, 1)

In [ ]:
thetas_of_normal_equation = np.dot(first,second)

In [ ]:
thetas_of_normal_equation

array([[ 81920.        ],
       [   339.98034335],
       [   214.98626732],
       [   177.36967915],
       [   756.31637963],
       [ 22947.20476479],
       [-73728.        ],
       [-90112.        ],
       [-73728.        ],
       [-65536.        ]])

In [ ]:
normal_equation_cost = mean_square_error(x_train,thetas_of_normal_equation,y_train)
normal_equation_cost

array([2.09175961e+08])